/* Configuration for uml2code generated by Alire */
#ifndef UML2CODE_CONFIG_H
#define UML2CODE_CONFIG_H

#define CRATE_VERSION "0.1.0"
#define CRATE_NAME "uml2code"

#define ALIRE_HOST_OS "macos"

#define ALIRE_HOST_ARCH "aarch64"

#define ALIRE_HOST_DISTRO "homebrew"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  1

#endif
