#!/usr/bin/env bash
# commit_manifests.sh
set -euo pipefail

cd ~/Projects/ai-generated

# 1. Add exceptions so the release manifests are tracked
cat >> .gitignore <<'EOF'

# Track publish manifests (generated by `alr publish`)
!plantuml_parser/alire/releases/
!hsm_runtime/alire/releases/
EOF

# 2. Add a Publishing section to README
python3 - README.md <<'PYEOF'
import sys
path = sys.argv[1]
with open(path) as f:
    src = f.read()

anchor = "See `AGENTS.md` for architecture notes and known gotchas.\n"
addition = '''See `AGENTS.md` for architecture notes and known gotchas.

## Publishing

`plantuml_parser` and `hsm_runtime` are both ready to publish to the
Alire community index. Their index manifests are committed under each
crate's `alire/releases/` directory:

- `plantuml_parser/alire/releases/plantuml_parser-0.1.0.toml`
- `hsm_runtime/alire/releases/hsm_runtime-0.1.0.toml`

To submit a new version:

    cd plantuml_parser && alr publish
    cd ../hsm_runtime && alr publish

Each opens a PR against `alire-project/alire-index`. Requires a GitHub
Personal Access Token configured for `alr`; see
https://github.com/alire-project/alire/blob/master/doc/publishing.md

Publishing is deferred until there is a reason to (first outside user,
or a feature-complete milestone).
'''

if addition.strip() not in src:
    src = src.replace(anchor, addition, 1)
    with open(path, 'w') as f:
        f.write(src)
    print("README updated")
else:
    print("README already has a Publishing section")
PYEOF

# 3. Stage everything
git add -A
git status --short

# 4. Commit
git commit -m "Track Alire publish manifests and document publishing process"

git log --oneline | head -3